
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.peter.typesecure.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETE_CERRADO = 40;
  public static final int SQRT2 = 64;
  public static final int DIVISION = 19;
  public static final int MENOR_IGUAL = 30;
  public static final int MENOR_QUE = 29;
  public static final int FLOOR = 71;
  public static final int BIGINT = 3;
  public static final int CHARAT = 47;
  public static final int TOUPPERCASE = 49;
  public static final int RVOID = 12;
  public static final int RLET = 14;
  public static final int TOLOWERCASE = 48;
  public static final int EXP = 70;
  public static final int SIN = 68;
  public static final int CORCHETE_ABIERTO = 39;
  public static final int TEXTO = 5;
  public static final int FBOOLEAN = 44;
  public static final int RANDOM = 74;
  public static final int POW = 72;
  public static final int MAYOR_QUE = 31;
  public static final int DISTINTO = 34;
  public static final int RSTRING = 10;
  public static final int FALSE = 7;
  public static final int NOT = 28;
  public static final int DOS_PUNTOS = 37;
  public static final int CEIL = 66;
  public static final int PUNTO_COMA = 38;
  public static final int MOD = 18;
  public static final int TAN = 69;
  public static final int FSTRING = 45;
  public static final int LOG = 52;
  public static final int RBIGINT = 9;
  public static final int INCREMENTO = 23;
  public static final int NUMBER = 2;
  public static final int COMA = 36;
  public static final int TRUE = 6;
  public static final int WHILE = 56;
  public static final int DO = 57;
  public static final int FOR = 55;
  public static final int DECREMENTO = 24;
  public static final int FBIGINT = 43;
  public static final int RETURN = 60;
  public static final int CONCAT = 50;
  public static final int ELSE = 54;
  public static final int MENOS = 16;
  public static final int MAS = 15;
  public static final int BREAK = 58;
  public static final int LENGTH = 46;
  public static final int PI = 63;
  public static final int COS = 67;
  public static final int E = 62;
  public static final int EOF = 0;
  public static final int PUNTO = 35;
  public static final int FUNCTION = 41;
  public static final int GETSYMBOLTABLE = 76;
  public static final int PRINTAST = 75;
  public static final int CONSOLE = 51;
  public static final int OR = 27;
  public static final int error = 1;
  public static final int CONTINUE = 59;
  public static final int IF = 53;
  public static final int PARENTESIS_CERRADO = 22;
  public static final int ID = 4;
  public static final int ABS = 65;
  public static final int UMENOS = 20;
  public static final int MULTIPLICACION = 17;
  public static final int RCONST = 13;
  public static final int RBOOLEAN = 11;
  public static final int SQRT = 73;
  public static final int COMPARACION = 33;
  public static final int ASIGNACION = 25;
  public static final int RNUMBER = 8;
  public static final int PARENTESIS_ABIERTO = 21;
  public static final int FNUMBER = 42;
  public static final int AND = 26;
  public static final int MATH = 61;
  public static final int MAYOR_IGUAL = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "BIGINT",
  "ID",
  "TEXTO",
  "TRUE",
  "FALSE",
  "RNUMBER",
  "RBIGINT",
  "RSTRING",
  "RBOOLEAN",
  "RVOID",
  "RCONST",
  "RLET",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "MOD",
  "DIVISION",
  "UMENOS",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "INCREMENTO",
  "DECREMENTO",
  "ASIGNACION",
  "AND",
  "OR",
  "NOT",
  "MENOR_QUE",
  "MENOR_IGUAL",
  "MAYOR_QUE",
  "MAYOR_IGUAL",
  "COMPARACION",
  "DISTINTO",
  "PUNTO",
  "COMA",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "FUNCTION",
  "FNUMBER",
  "FBIGINT",
  "FBOOLEAN",
  "FSTRING",
  "LENGTH",
  "CHARAT",
  "TOLOWERCASE",
  "TOUPPERCASE",
  "CONCAT",
  "CONSOLE",
  "LOG",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "DO",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "MATH",
  "E",
  "PI",
  "SQRT2",
  "ABS",
  "CEIL",
  "COS",
  "SIN",
  "TAN",
  "EXP",
  "FLOOR",
  "POW",
  "SQRT",
  "RANDOM",
  "PRINTAST",
  "GETSYMBOLTABLE"
  };
}

