
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.peter.typesecure.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 19;
  public static final int MENOS = 16;
  public static final int MULTIPLICACION = 17;
  public static final int PARENTESIS_ABIERTO = 21;
  public static final int BIGINT = 3;
  public static final int DIVISION = 18;
  public static final int RSTRING = 10;
  public static final int TRUE = 6;
  public static final int UMENOS = 20;
  public static final int ID = 4;
  public static final int RBOOLEAN = 11;
  public static final int PARENTESIS_CERRADO = 22;
  public static final int RVOID = 12;
  public static final int ASIGNACION = 25;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int RCONST = 13;
  public static final int INCREMENTO = 23;
  public static final int FALSE = 7;
  public static final int TEXTO = 5;
  public static final int error = 1;
  public static final int DECREMENTO = 24;
  public static final int RNUMBER = 8;
  public static final int RBIGINT = 9;
  public static final int MAS = 15;
  public static final int RLET = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "BIGINT",
  "ID",
  "TEXTO",
  "TRUE",
  "FALSE",
  "RNUMBER",
  "RBIGINT",
  "RSTRING",
  "RBOOLEAN",
  "RVOID",
  "RCONST",
  "RLET",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "DIVISION",
  "MOD",
  "UMENOS",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "INCREMENTO",
  "DECREMENTO",
  "ASIGNACION"
  };
}

